CREATE TABLE Movies (
	idMovie INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Title VARCHAR(500) NOT NULL,
	Category VARCHAR(100) NULL,
	DateRelease INT NULL,
	Family VARCHAR(50) NULL,
	Country VARCHAR(50) NULL,
	Is_Good BIT NOT NULL DEFAULT(0),
	Year_Good INT NULL)
GO

